### ISSUE TITLE
Grab bag of small issues

### ISSUE THREAD

**Issue by robinwhittleton** [jmcphers/a-w-tozer_the-pursuit-of-god#1]
`se clean` removes a blank line from local.css

**content.opf:**
- longdesc: A. W. needs to be wrapped with an abbr
- longdesc: italicise “The Pursuit of God” and remove quotes
- longdesc: Christianity Today is a publication, so we’d want to italicise it
- Your homepage should be https to match the colophon

**introduction:**
- `<section id="introduction">` needs an `epub:type="introduction"`
- M. needs an abbr in the signature

**preface:**
- `<section id="preface">` needs an `epub:type="preface"`
- Ill. needs to be wrapped with an abbr

**chapter-5:**
- couple of changes made by modernize-spelling that I agree with

**chapter-10:**
- `<i>God is holy</i>` should presumably be `<em>` instead

**endnotes:**
- _The Vision of God_ needs `epub:type="se:name.publication.book"`
- E. P. needs an `<abbr epub:type="z3998:given-name">`

**colophon:**
- artist name needs to be wrapped with a `<b epub:type="z3998:personal-name">`

Once you’ve done those and run lint again you’ll notice a couple more errors about missing roles in the metadata. That’s because we’ve added `epub:type="introduction"` and `epub:type="preface"`. You should add `<meta property="se:role" refines="#author" scheme="marc:relators">wpr</meta>` for A. W. Tozer. You’ll then need to add a new `dc:contributor` block for Samuel M. Zwemer with a `win` (writer of introduction) role.

**Comment by jmcphers** [comment]
Very much appreciate the review! I've taken care of each of these items.

**Comment by robinwhittleton** [comment]
One change: in note-2 of the endnotes, you’ve added `<abbr epub:type="z3998:given-name">E. P. Dutton</abbr>`; it should match the other notes with `<abbr epub:type="z3998:given-name">E. P.</abbr> Dutton`. Apart from that it looks great.

**Comment by jmcphers** [comment]
Oh, thanks for catching that! Fixed via https://github.com/jmcphers/a-w-tozer_the-pursuit-of-god/commit/3f9537c3c2a1708b371c2cb6a618bf1b5109ac5e.
